site_name: PC Matic Install Guide
site_url: https://example.com
repo_url: https://github.com/clarkdarlton/pcmaticstart
repo_name: pcmatic-guide

theme:
  name: material
  language: en

nav:
  - Home: index.md
  - Install Guide: install.md
  - Activation: activation.md
  - Support: support.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
